<?php
session_start();
$publicaciones=$_SESSION['array_publicaciones'];
require '../common/conexion.php';require '../common/take_at.php';require '../common/account-off.php';require '../common/callback.php';
$ch=curl_init();
if(isset($_GET['page'])){
$offset=50*($_GET['page']-1);
curl_setopt($ch,CURLOPT_URL,'https://api.mercadolibre.com/users/'.$id_user.'/items/search?status=active&access_token='.$AccessToken.'&offset='.$offset.'&callback='.$callback);
}else{echo 'false';}
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
$result=curl_exec($ch);
curl_close($ch);
$length=strlen($result)-6;
$string=substr($result,4,$length);
$var=json_decode($string);
$consulta=$var[2];
$array_publicaciones=$consulta->results;
$auxiliar='';
$total_items=count($array_publicaciones);
$contador=0;
$band=0;
if($total_items>0){
while($contador!=$total_items){
$array_publicaciones_veinte=array();
$aux=$contador+19;
for($i=$contador;$i<=$aux;$i++){
if(isset($array_publicaciones[$i])){
++$contador;
array_push($array_publicaciones_veinte,$array_publicaciones[$i]);
}
}
$str_public=implode(',',$array_publicaciones_veinte);
$array_publicaciones_veinte=array();
$ch=curl_init();
curl_setopt($ch,CURLOPT_URL,'https://api.mercadolibre.com/items?ids='.$str_public.'&attributes=id,title,thumbnail&access_token='.$AccessToken.'&callback='.$callback);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
$result2=curl_exec($ch);
curl_close($ch);
$length=strlen($result2)-6;
$string=substr($result2,4,$length);
$var=json_decode($string);
$consulta2=$var[2];
foreach($consulta2 as $valor){
$id=$valor->body->id;
$title=$valor->body->title;
$thumbnail=$valor->body->thumbnail;
$aux=$id.'~¬'.$title;
$band2=array_search($aux,$publicaciones);
if($auxiliar==''){
if(@$publicaciones[0]==1){
if($band2===false){
$auxiliar=$id.'¬'.$title.'¬'.$thumbnail.'¬1';
}else{$auxiliar=$id.'¬'.$title.'¬'.$thumbnail.'¬0';}
}else{
if($band2===false){
$auxiliar=$id.'¬'.$title.'¬'.$thumbnail.'¬0';
}else{$auxiliar=$id.'¬'.$title.'¬'.$thumbnail.'¬1';}
}
}else{
if(@$publicaciones[0]==1){
if($band2===false){
$auxiliar.='|'.$id.'¬'.$title.'¬'.$thumbnail.'¬1';
}else{$auxiliar.='|'.$id.'¬'.$title.'¬'.$thumbnail.'¬0';}
}else{
if($band2===false){
$auxiliar.='|'.$id.'¬'.$title.'¬'.$thumbnail.'¬0';
}else{$auxiliar.='|'.$id.'¬'.$title.'¬'.$thumbnail.'¬1';}
}
}
}
}
echo $auxiliar;
}
?>
