#CREAR BASE DE DATOS
CREATE DATABASE OXA;


#CREACION DE TABLAS
CREATE TABLE USUARIO (
    IDUSUARIO int NOT NULL,
    CORREO varchar(255),
    SALUDO varchar(255),
    DESPEDIDA varchar(255),
    ACCESSTOKEN varchar(255),
    REFRESTOKEN varchar(255),

     PRIMARY KEY (IDUSUARIO),
     UNIQUE (CORREO)
);

CREATE  TABLE PUBLICACION (
    IDPUBLICACION int NOT NULL AUTO_INCREMENT,
    IDUSUARIO int NOT NULL,
    CODIGO varchar(255),
    NOMBRE varchar(60),
    PRIMARY KEY (IDPUBLICACION),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    ON DELETE CASCADE
);

CREATE TABLE SINAPSIS (
    IDSINAPSIS int NOT NULL AUTO_INCREMENT,
    IDUSUARIO int NOT NULL,
    INFO TEXT,
    ESTIMULOS TEXT,
    NUMPUBLICACIONES INT,

    PRIMARY KEY (IDSINAPSIS),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    ON DELETE CASCADE
    );

CREATE TABLE ENLACE (
    IDENLACE int NOT NULL AUTO_INCREMENT,
    IDSINAPSIS int NOT NULL ,
    IDPUBLICACION int NOT NULL,

    PRIMARY KEY (IDENLACE),
    FOREIGN KEY (IDPUBLICACION) REFERENCES PUBLICACION(IDPUBLICACION) ON DELETE CASCADE,
    FOREIGN KEY (IDSINAPSIS) REFERENCES SINAPSIS(IDSINAPSIS)
    ON DELETE CASCADE
);


CREATE TABLE SUSCRIPCION (
    IDSUSCRIPCION int NOT NULL AUTO_INCREMENT,
    IDUSUARIO int,
    FECHAVENCIMIENTO DATE, #yyyy-mm-dd
    TIPOSUSCRIPCION int,
    ESTATUS int,

    PRIMARY KEY (IDSUSCRIPCION),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
    ON DELETE CASCADE
);

/*
Nuevas Tablas
*/
CREATE TABLE `plan`(
  `IDPLAN` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(30) DEFAULT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  `TIEMPO` INT,
  `MONTO` FLOAT DEFAULT 0.0 ,

  PRIMARY KEY (IDPLAN)
);

CREATE TABLE `pagos`(
  `IDPAGO` int NOT NULL AUTO_INCREMENT,
  `IDUSUARIO` int NOT NULL,
  `BANCOE` varchar(100) DEFAULT NULL,
  `BANCOR` varchar(100) DEFAULT NULL,
  `FECHA` DATE,
  `MONTO` FLOAT DEFAULT 0.0 ,
  `REFERENCIA` BOOLEAN NULL DEFAULT FALSE,
  `ESTATUS` BOOLEAN NULL DEFAULT FALSE,

  PRIMARY KEY (IDPAGO),
  FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
  ON DELETE CASCADE
);

CREATE TABLE `facturas`(
  `IDFACTURA` int NOT NULL AUTO_INCREMENT,
  `IDUSUARIO`int NOT NULL,
  `FACHAEMISION` DATETIME,
  `MONTO` FLOAT DEFAULT 0.0  ,
  `DESCRIPCION` varchar(255) DEFAULT NULL,

  PRIMARY KEY (IDFACTURA),
  FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
  ON DELETE CASCADE
);

CREATE TABLE `servicios`(
  `IDSERVICIOS` int NOT NULL AUTO_INCREMENT,
  `IDUSUARIO` int NOT NULL,
  `IDPLAN` int NOT NULL  DEFAULT 1,

  PRIMARY KEY (IDSERVICIOS),
  FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
  ON DELETE CASCADE
);
/*
Fin de Nuevas Tablas
*/
